name: E2E Preview
on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  e2e:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: 'npm' }

      - run: npm ci

      # Wait for Vercel preview deployment created by your GitHub → Vercel integration
      - name: Wait for Vercel preview
        id: vercel
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 600

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run E2E (smoke)
        run: npm run e2e:ci
        env:
          BASE_URL: ${{ steps.vercel.outputs.url }}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "test"  # use your test Clerk publishable key if needed
        
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: playwright-report
            path: playwright-report
        